# Generated by Django 4.1.3 on 2022-11-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='book',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='history',
            name='book',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='book',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
