# Generated by Django 4.1.3 on 2022-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bookstoreuser_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
