# Generated by Django 4.1.3 on 2022-11-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0004_alter_shoppingcart_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product_count',
            new_name='book_count',
        ),
        migrations.AlterField(
            model_name='favourites',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='history',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
