# Generated by Django 4.1.3 on 2022-11-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_product_count_shoppingcart_book_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='type',
            field=models.CharField(choices=[('A', 'Audio'), ('S', 'Standard'), ('E', 'Electronic')], max_length=1, null=True),
        ),
    ]
