# Generated by Django 4.1.3 on 2022-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_shoppingcart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoreuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
