# Generated by Django 4.1.3 on 2022-11-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bookstoreuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_of_view',
            field=models.DateField(null=True),
        ),
    ]
