# Generated by Django 4.1.3 on 2022-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_history_date_of_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoreuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
