# Generated by Django 4.1.3 on 2022-11-01 14:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5.0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('author', models.CharField(max_length=100)),
                ('translator', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('article', models.PositiveBigIntegerField()),
                ('isbn', models.PositiveBigIntegerField()),
                ('pages', models.PositiveSmallIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('is_on_sale', models.BooleanField(default=True)),
                ('count', models.PositiveIntegerField()),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
