# Generated by Django 4.1.3 on 2022-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_article_book_article_number_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='article_number',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
